# Generated by Django 5.2.1 on 2025-05-14 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=8, unique=True, verbose_name='DNI')),
                ('name', models.CharField(max_length=100, verbose_name='Nombres')),
                ('position', models.CharField(max_length=100, verbose_name='Cargo')),
                ('join_date', models.DateField(verbose_name='Fecha de Ingreso')),
                ('shift_type', models.CharField(choices=[('turno_1', 'Turno 1 (9:00-14:00 y 18:00-22:00)'), ('turno_continuo', 'Turno Continuo (10:00-18:00)'), ('turno_3', 'Turno 3 (14:00-22:00)')], max_length=20, verbose_name='Tipo de Turno')),
                ('rest_day', models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miércoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sábado', 'Sábado'), ('domingo', 'Domingo')], max_length=20, verbose_name='Día de Descanso')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company', verbose_name='Empresa')),
            ],
        ),
    ]
