# Generated by Django 5.2.1 on 2025-05-14 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_termination_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='shift_type',
            field=models.CharField(choices=[('turno_1', 'Turno 1 (10:00-14:00 y 18:00-22:00)'), ('turno_2', 'Turno 2 (10:00-01:30 y 14:30-19:00)'), ('turno_3', 'Turno 3 (13:00-16:30 y 17:30-22:00)')], max_length=20, verbose_name='Tipo de Turno'),
        ),
    ]
