# Generated by Django 5.2.1 on 2025-05-14 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('check_in_morning', models.TimeField(blank=True, null=True, verbose_name='Entrada Mañana')),
                ('check_out_morning', models.TimeField(blank=True, null=True, verbose_name='Salida Mañana')),
                ('check_in_afternoon', models.TimeField(blank=True, null=True, verbose_name='Entrada Tarde')),
                ('check_out_afternoon', models.TimeField(blank=True, null=True, verbose_name='Salida Tarde')),
            ],
        ),
    ]
